# version: "3.8"
# References: https://www.emqx.io/docs/en/latest/deploy/install-docker.html
services:
  # MQTT listeners
  mqtt-listener-1:
    image: emqx-learning/mqtt-listner:latest
    # logging:
    #   driver: none
    build:
      context: .
      dockerfile: EmqxLearning.MqttListener/Dockerfile
    environment:
      Logging__LogLevel__Default: Warning
      MqttClientOptions__TcpServer: node1.emqx.io
      MqttClientOptions__CleanSession: false
      MqttClientOptions__SessionExpiryInterval: 120
      MqttClientOptions__ReconnectDelaySecs: 3
      MqttClientOptions__Topic: $$share/ahi/projectId/+/devices/+/telemetry
      MqttClientOptions__Qos: 1
      ReceiveDelay: 0
      ProcessingTime: 20
      InitialConcurrencyLimit: 8
      NumberOfConnections: 20
      BackgroundProcessing: true
      ScaleFactor: 50
      ScaleCheckInterval: 5000
      RabbitMqClient__HostName: rabbitmq1
    networks:
      - emqx-bridge
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "500M"
    depends_on:
      emqx1:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy

  # MQTT publishers
  mqtt-publisher-1:
    image: emqx-learning/mqtt-publisher:latest
    build:
      context: .
      dockerfile: EmqxLearning.MqttPublisher/Dockerfile
    environment:
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__TopicFormat=projectId/{0}/devices/{1}/telemetry
    stdin_open: true
    tty: true
    networks:
      - emqx-bridge
    deploy:
      replicas: 3
    depends_on:
      emqx1:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy

  kafka-consumer-1:
    image: emqx-learning/kafka-consumer:latest
    build:
      context: .
      dockerfile: EmqxLearning.KafkaConsumer/Dockerfile
    environment:
      Logging__LogLevel__Default: Warning
      ProcessingTime: 50
      ConsumerCount: 2
      InsertDb: false
      BatchSettings__Enabled: true
      BatchSettings__BatchInterval: 190
      BatchSettings__BatchSize: 200
      BatchSettings__WorkerThreadCount: 5
      ConnectionStrings__DeviceDb: Maximum Pool Size=10;User ID=postgres;Password=zaQ@123456!;Host=timescaledb1;Port=5432;Database=device;Pooling=true;
    networks:
      - emqx-bridge
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "4"
          memory: "500M"
    depends_on:
      rabbitmq1:
        condition: service_healthy
      timescaledb1:
        condition: service_started
  
  # RabbitMQ consumers
  # rabbitmq-consumer-1:
  #   image: emqx-learning/rabbitmq-consumer:latest
  #   # logging:
  #   #   driver: none
  #   build:
  #     context: .
  #     dockerfile: EmqxLearning.RabbitMqConsumer/Dockerfile
  #   environment:
  #     Logging__LogLevel__Default: Warning
  #     ProcessingTime: 50
  #     ConsumerCount: 2
  #     InsertDb: false
  #     BatchSettings__Enabled: true
  #     BatchSettings__BatchInterval: 190
  #     BatchSettings__BatchSize: 200
  #     BatchSettings__WorkerThreadCount: 5
  #     ConnectionStrings__DeviceDb: Maximum Pool Size=10;User ID=postgres;Password=zaQ@123456!;Host=timescaledb1;Port=5432;Database=device;Pooling=true;
  #     RabbitMqClient__HostName: rabbitmq1
  #     RabbitMqClient__DispatchConsumersAsync: true
  #     RabbitMqClient__ConsumerDispatchConcurrency: 5
  #     RabbitMqChannel__PrefetchCount: 2500
  #   networks:
  #     - emqx-bridge
  #   deploy:
  #     replicas: 2
  #     resources:
  #       limits:
  #         cpus: "4"
  #         memory: "500M"
  #   depends_on:
  #     rabbitmq1:
  #       condition: service_healthy
  #     timescaledb1:
  #       condition: service_started

  # rabbitmq-function-1:
  #   image: emqx-learning/rabbitmq-function:latest
  #   build:
  #     context: .
  #     dockerfile: EmqxLearning.RabbitMqFunction/Dockerfile
  #   environment:
  #     AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;"
  #     FUNCTIONS_WORKER_RUNTIME: "dotnet"
  #     AzureServiceBus__Host: "rabbitmq1"
  #     AzureServiceBus__KeyName: "admin"
  #     AzureServiceBus__SharedAccessKey: "zaQ@123456!"
  #     RabbitMQ: "amqp://admin:zaQ%40123456!@rabbitmq1:5672"
  #     DataFolder: "/var/device/data"
  #     AzureFunctionsJobHost__logging__LogLevel__Default: "Warning"
  #     ProcessingTime: 50
  #   networks:
  #     - emqx-bridge
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: "250M"
  #   depends_on:
  #     rabbitmq1:
  #       condition: service_healthy

  # EMQTT bench mark
  # emqtt-bench:
  #   image: emqx-learning/custom-emqtt-bench:latest
  #   logging:
  #     driver: none
  #   build:
  #     context: .
  #     dockerfile: deployment/emqtt-bench/Dockerfile
  #   networks:
  #     - emqx-bridge
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - HOST=node1.emqx.io

  # EMQX nodes
  emqx1:
    image: emqx/emqx:5.6.0
    container_name: emqx1
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_MQTT__MAX_MQUEUE_LEN=1000000"
      - "EMQX_MQTT__MAX_INFLIGHT=128"
      # - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      # - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    # volumes:
    #   - $PWD/emqx1_data:/opt/emqx/data

  # emqx2:
  #   image: emqx/emqx:5.6.0
  #   container_name: emqx2
  #   environment:
  #     - "EMQX_NODE_NAME=emqx@node2.emqx.io"
  #     - "EMQX_MQTT__MAX_MQUEUE_LEN=1000000"
  #     - "EMQX_MQTT__MAX_INFLIGHT=128"
  #     - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
  #     - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
  #   healthcheck:
  #     test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
  #     interval: 5s
  #     timeout: 25s
  #     retries: 5
  #   networks:
  #     emqx-bridge:
  #       aliases:
  #         - node2.emqx.io
  #   # volumes:
  #   #   - $PWD/emqx2_data:/opt/emqx/data

  # RabbitMQ nodes
  rabbitmq1:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./deployment/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./deployment/rabbitmq/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - emqx-bridge
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "2G"

  # TimescaleDB
  timescaledb1:
    image: "timescale/timescaledb-ha:pg14-arm64"
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./deployment/timescaledb/scripts:/docker-entrypoint-initdb.d
      - ./deployment/timescaledb/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: "zaQ@123456!"
      POSTGRES_DB: "device"
    networks:
      - emqx-bridge
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "6"
          memory: "2G"

  # Azure services
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - emqx-bridge
      
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - emqx-bridge

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    networks:
      - emqx-bridge

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
      DYNAMIC_CONFIG_ENABLED: true # not necessary for sasl auth, added for tests
    networks:
      - emqx-bridge


  kafka-init-topics:
    image: confluentinc/cp-kafka:7.2.1
    volumes:
       - ./data/message.json:/data/message.json
    depends_on:
      - kafka1
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
               cub kafka-ready -b kafka:29092 1 30 && \
               kafka-topics --create --topic users --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 && \
               kafka-topics --create --topic messages --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 && \
               kafka-console-producer --bootstrap-server kafka:29092 --topic users < /data/message.json'"

    networks:
      - emqx-bridge
  
networks:
  emqx-bridge:
    driver: bridge
