version: "3.8"
# References: https://www.emqx.io/docs/en/latest/deploy/install-docker.html
services:
  mqtt-listener-1:
    image: emqx-learning/mqtt-listner:latest
    # logging:
    #   driver: none
    build:
      context: .
      dockerfile: EmqxLearning.MqttListener/Dockerfile
    environment:
      - Logging__LogLevel__Default=Error
      - MqttClientOptions__ClientId=mqtt-listener-1
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__CleanSession=true
      - MqttClientOptions__ReconnectDelaySecs=5
      - MqttClientOptions__Topic=$$share/ahi/projectId/+/devices/+/telemetry
      - MqttClientOptions__Qos=1
      - ReceiveDelay=3
      - ProcessingTime=50
      - ProcessingThreads=20
      - BackgroundProcessing=true
    networks:
      - emqx-bridge
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500M"

  mqtt-listener-2:
    image: emqx-learning/mqtt-listner:latest
    # logging:
    #   driver: none
    build:
      context: .
      dockerfile: EmqxLearning.MqttListener/Dockerfile
    environment:
      - Logging__LogLevel__Default=Error
      - MqttClientOptions__ClientId=mqtt-listener-2
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__CleanSession=true
      - MqttClientOptions__ReconnectDelaySecs=5
      - MqttClientOptions__Topic=$$share/ahi/projectId/+/devices/+/telemetry
      - MqttClientOptions__Qos=1
      - ReceiveDelay=3
      - ProcessingTime=50
      - ProcessingThreads=20
      - BackgroundProcessing=true
    networks:
      - emqx-bridge
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500M"

  mqtt-listener-3:
    image: emqx-learning/mqtt-listner:latest
    # logging:
    #   driver: none
    build:
      context: .
      dockerfile: EmqxLearning.MqttListener/Dockerfile
    environment:
      - Logging__LogLevel__Default=Error
      - MqttClientOptions__ClientId=mqtt-listener-3
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__CleanSession=true
      - MqttClientOptions__ReconnectDelaySecs=5
      - MqttClientOptions__Topic=$$share/ahi/projectId/+/devices/+/telemetry
      - MqttClientOptions__Qos=1
      - ReceiveDelay=3
      - ProcessingTime=50
      - ProcessingThreads=20
      - BackgroundProcessing=true
    networks:
      - emqx-bridge
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500M"

  mqtt-publisher-1:
    image: emqx-learning/mqtt-publisher:latest
    build:
      context: .
      dockerfile: EmqxLearning.MqttPublisher/Dockerfile
    environment:
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__TopicFormat=projectId/{0}/devices/{1}/telemetry
    stdin_open: true
    tty: true
    networks:
      - emqx-bridge

  mqtt-publisher-2:
    image: emqx-learning/mqtt-publisher:latest
    build:
      context: .
      dockerfile: EmqxLearning.MqttPublisher/Dockerfile
    environment:
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__TopicFormat=projectId/{0}/devices/{1}/telemetry
    stdin_open: true
    tty: true
    networks:
      - emqx-bridge

  mqtt-publisher-3:
    image: emqx-learning/mqtt-publisher:latest
    build:
      context: .
      dockerfile: EmqxLearning.MqttPublisher/Dockerfile
    environment:
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__TopicFormat=projectId/{0}/devices/{1}/telemetry
    stdin_open: true
    tty: true
    networks:
      - emqx-bridge

  mqtt-publisher-4:
    image: emqx-learning/mqtt-publisher:latest
    build:
      context: .
      dockerfile: EmqxLearning.MqttPublisher/Dockerfile
    environment:
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__TopicFormat=projectId/{0}/devices/{1}/telemetry
    stdin_open: true
    tty: true
    networks:
      - emqx-bridge

  mqtt-publisher-5:
    image: emqx-learning/mqtt-publisher:latest
    build:
      context: .
      dockerfile: EmqxLearning.MqttPublisher/Dockerfile
    environment:
      - MqttClientOptions__TcpServer=node1.emqx.io
      - MqttClientOptions__TopicFormat=projectId/{0}/devices/{1}/telemetry
    stdin_open: true
    tty: true
    networks:
      - emqx-bridge

  # emqtt-bench:
  #   image: emqx-learning/custom-emqtt-bench:latest
  #   logging:
  #     driver: none
  #   build:
  #     context: .
  #     dockerfile: deployment/emqtt-bench/Dockerfile
  #   networks:
  #     - emqx-bridge
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - HOST=node1.emqx.io

  emqx1:
    image: emqx/emqx:5.6.0
    container_name: emqx1
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_MQTT__MAX_MQUEUE_LEN=1000000"
      - "EMQX_MQTT__MAX_INFLIGHT=128"
      # - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      # - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    # volumes:
    #   - $PWD/emqx1_data:/opt/emqx/data

  # emqx2:
  #   image: emqx/emqx:5.6.0
  #   container_name: emqx2
  #   environment:
  #     - "EMQX_NODE_NAME=emqx@node2.emqx.io"
  #     - "EMQX_MQTT__MAX_MQUEUE_LEN=1000000"
  #     - "EMQX_MQTT__MAX_INFLIGHT=128"
  #     - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
  #     - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
  #   healthcheck:
  #     test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
  #     interval: 5s
  #     timeout: 25s
  #     retries: 5
  #   networks:
  #     emqx-bridge:
  #       aliases:
  #         - node2.emqx.io
  #   # volumes:
  #   #   - $PWD/emqx2_data:/opt/emqx/data

networks:
  emqx-bridge:
    driver: bridge
